### Numpy的优势

NumPy(Numerical Python)之所以如此重要，其中一个原因就是它的设计对于含有大量数组的数据非常有效。此外还有两个原因：

1、NumPy在内部将数据存储在连续的内存块上，这与其他的Python内建数据结构不同。NumPy的算法库是用C语言写的，所以在操作数据内存时，不需要任何类型检查或者其他管理操作。NumPy数组使用的内存量也小于其他Python内建序列。
2、NumPy可以针对全量数组进行复杂计算而不需要写Python循环。  

Numpy方法比Python方法要快10到100倍，并且使用的内存也更少:

In [1]:
import numpy as np
np.set_printoptions(suppress=True)        # 设置输出为非科学计数法

In [2]:
myArr = np.arange(1000000)
myList = list(range(1000000))

%time for _ in range(10): myArr2 = myArr * 2
%time for _ in range(10): myList2 = [x * 2 for x in myList]

Wall time: 31.9 ms
Wall time: 1.26 s


### 生成ndarray

In [3]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
# 同等长度的列表，会自动转换成多维数组
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
print("秩: ", arr2.ndim)
print("维度: ", arr2.shape)
print("数据类型: ", arr2.dtype)
print("元素的个数: ", arr2.size)
print("每个元素的大小: ", arr2.itemsize)

秩:  2
维度:  (2, 4)
数据类型:  int32
元素的个数:  8
每个元素的大小:  4


### 一些特殊函数

In [6]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### ndarray的数据类型

In [11]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 3, 3], dtype=np.int32)

print(arr1.dtype, '/', arr2.dtype)

float64 / int32


可以使用astype方法显式地转换数组的数据类型:

In [12]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)
floatArr = arr.astype(np.float64)
floatArr.dtype

dtype('float64')

如将浮点数转换为整数，则小数点后的部分会被消除:

In [13]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9])
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12])

可以将字符串转换为数字:

In [14]:
numericStrings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numericStrings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

可以使用另一个数组的dtype属性:

In [15]:
intArray = np.arange(10)
calibers = np.array([0.22, 0.270, 0.357, 0.380], dtype=np.float64)
intArray.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Numpy数组算数

In [16]:
arr = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [17]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

带有标量计算的算数操作，会把计算参数传递给数组的每一个元素:

In [18]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

同尺寸数组之间比较，会产生一个布尔值数组:

In [19]:
arr2 = np.array([[0.0, 4.0, 1.0], [7.0, 2.0, 12.0]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### 基础索引与切片

In [20]:
arr = np.arange(10)
# 索引从0开始
arr[5]

5

In [21]:
# 含头不含尾
arr[5:8]

array([5, 6, 7])

In [22]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

区别于Python的内建列表，数组的切片是原数组的视图，意味着数据并不是被复制了，任何对于视图的修改都会反映到原数组上:

In [23]:
arrSlice = arr[5:8]
arrSlice

array([12, 12, 12])

In [24]:
arrSlice[1] = 123
arr

array([  0,   1,   2,   3,   4,  12, 123,  12,   8,   9])

改变arrSlice的值时，变化也会体现在原数组上。如果需要一份数组切片的拷贝而不是视图的话，必须显式地复制这个数组:

In [25]:
arr = np.arange(10)
arrCopy = arr[5:8].copy()
arrCopy[:] = 34
arrCopy

array([34, 34, 34])

In [26]:
# 对于副本的修改没有体现到原数组上
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

对于更高维度的数组:

In [27]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [28]:
arr2d[2, 1]

8

在多维数组中，可以省略后续索引值，返回的对象将是降低一个维度的数组:

In [29]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
arr3d[0]        # arr3d[0]是一个2x3的数组

array([[1, 2, 3],
       [4, 5, 6]])

标量和数组都可以传递给arr3d\[0\]:

In [31]:
oldValues = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
arr3d[0] = oldValues
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
arr3d[1, 0]

array([7, 8, 9])

### 数组转置与换轴
转置是一种特殊的数据重组形式，可以返回底层数据的视图而不需要复制任何内容:

In [34]:
arr = np.arange(12).reshape((3, -1))
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

转置可以用于计算矩阵的内积:

In [35]:
np.dot(arr.T, arr)

array([[ 80,  92, 104, 116],
       [ 92, 107, 122, 137],
       [104, 122, 140, 158],
       [116, 137, 158, 179]])

对于更高维度的数组，transpose方法可以接收包含轴编号的元组，用于置换轴:

In [36]:
arr = np.arange(16).reshape(2, 2, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [37]:
arr.transpose((1, 0, 2))               # 原先第一个轴和第二个轴互换，第三个轴不变

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

ndarray有一个swapaxes方法，该方法接收一对轴编号作为参数，并对轴进行调整用于重组数据:

In [38]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

### 通用函数：快速的逐元素函数

In [39]:
arr = np.arange(6)
np.sqrt(arr).round(2)

array([0.  , 1.  , 1.41, 1.73, 2.  , 2.24])

In [40]:
np.exp(arr).round(2)

array([  1.  ,   2.72,   7.39,  20.09,  54.6 , 148.41])

In [41]:
x = np.array([1, 3, 5, 2, 4, 6])
y = np.array([0, 8, 4, 7, 9, 6])
np.maximum(x, y)            # np.minimum(x, y)

array([1, 8, 5, 7, 9, 6])

也有一些通用函数返回多个数组，比如modf，是Python内建函数divmod的向量化版本，它返回一个浮点值数组的小数部分和整数部分:

In [42]:
arr = np.random.randn(6).round(4) * 5
arr

array([-3.7785, -1.9605, -5.5205,  3.8185, -6.6165,  2.8755])

In [43]:
remainder, wholePart = np.modf(arr)
print('WholePart: ', wholePart)
print('Remainder: ', remainder)

WholePart:  [-3. -1. -5.  3. -6.  2.]
Remainder:  [-0.7785 -0.9605 -0.5205  0.8185 -0.6165  0.8755]


### 其他通用函数  

一元通用函数
- abs
- sign 计算每个元素的符号值
- ceil 计算大于等于给定元素的最小整数
- floor 计算小于等于给定元素的最大整数
- rint 将元素保留到整数位，并保持dtype
- isnan 返回数组中的元素是否是一个NaN

二元通用函数
- add 将数组的对应元素相加
- substract 在第二个数组中，将第一个数组包含的元素去除
- multiply 将数组的对应元素相乘
- divide 除
- floor_divide 整除（放弃余数）
- power 将第二个数组的元素作为第一个数组对应元素的幂次方
- mod 求余

### 将条件逻辑作为数组操作
np.where函数是三元表达式 x if condition else y 的向量化版本:

In [44]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

# 当cond为True时取xarr中对应的元素，为False时取yarr中对应的元素
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

如果数组很大的话，速度会很慢，因为所有的工作都是通过Python解释器解释Python代码完成，并且当数组是多维时就不能使用该方法了。使用np.where可以非常简单地完成:

In [45]:
np.where(cond, xarr, yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

np.where在数据分析中的一个典型用法是根据一个数组来生成一个新的数组。假设现需将随机生成的数组中的正值替换为1，负值替换为0，可以:

In [46]:
arr = np.random.randn(4, 4).round(2)
arr

array([[-0.64, -1.15,  0.13, -0.04],
       [-0.76, -1.63, -0.45, -0.63],
       [ 0.83, -1.2 ,  1.29,  0.51],
       [ 0.44, -0.05, -0.06, -1.6 ]])

In [47]:
np.where(arr>0, 1, 0)

array([[0, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 1],
       [1, 0, 0, 0]])

可以将标量和数组联合，例如下面的代码可仅将arr中所有的正值替换为1:

In [48]:
np.where(arr>0, 1, arr)

array([[-0.64, -1.15,  1.  , -0.04],
       [-0.76, -1.63, -0.45, -0.63],
       [ 1.  , -1.2 ,  1.  ,  1.  ],
       [ 1.  , -0.05, -0.06, -1.6 ]])

### 数学和统计方法

In [49]:
arr = np.random.randn(5, 4).round(2)
arr

array([[ 0.09, -0.9 , -0.13, -1.2 ],
       [ 0.37,  0.23,  0.56, -0.02],
       [ 1.18,  1.64, -0.05,  0.05],
       [ 0.27,  1.5 ,  1.13, -2.58],
       [-0.65,  0.83,  0.  ,  0.49]])

In [50]:
arr.mean()         # equivalents to np.mean(arr)

0.14049999999999999

In [51]:
arr.mean(axis=1)          # 横向，共5行

array([-0.535 ,  0.285 ,  0.705 ,  0.08  ,  0.1675])

In [52]:
arr.sum(axis=0)           # 纵向，共4列

array([ 1.26,  3.3 ,  1.51, -3.26])

In [53]:
arr.sum()

2.8099999999999996

cumsum和cumprod 不会聚合，而是产生一个中间结果:

In [54]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [55]:
arr.cumprod()

array([  1,   2,   6,  24, 120, 720], dtype=int32)

在多维数组中，可以在指定轴向上根据较低维度的切片进行部分聚合:

In [56]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr.cumsum(axis=0)     # 在每列上累加

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [57]:
arr.cumprod(axis=1)   # 在每行上累乘

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

### 布尔值数组的方法
对于布尔型数组，有两个非常有用的方法any和all。any检查数组中是否至少有一个True，all检查是否每个值都是True:

In [58]:
bools = np.array([False, False, True, False])
bools.any()

True

In [59]:
bools.all()

False

### 排序

In [60]:
arr = np.random.randn(6).round(2)
arr

array([-0.34,  0.79,  2.26, -0.74, -2.67,  1.68])

In [61]:
arr.sort()
arr

array([-2.67, -0.74, -0.34,  0.79,  1.68,  2.26])

在多维数组中可以根据传递的axis值，沿着轴向对每个一维数据段进行排序:

In [62]:
arr = np.random.randn(5, 3).round(2)
arr

array([[-0.93,  1.22, -0.09],
       [ 1.84, -1.74, -0.01],
       [-0.76,  1.41, -0.22],
       [ 1.32,  0.59,  0.27],
       [ 0.31,  0.53, -0.55]])

In [63]:
arr.sort(1)       # 按行排序
arr

array([[-0.93, -0.09,  1.22],
       [-1.74, -0.01,  1.84],
       [-0.76, -0.22,  1.41],
       [ 0.27,  0.59,  1.32],
       [-0.55,  0.31,  0.53]])

### 唯一值

In [64]:
names = np.array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'])
np.unique(names)

array(['bob', 'joe', 'will'], dtype='<U4')

### 线性代数

numpy.linalg 拥有一个矩阵分解的标准函数集，以及其他常用函数：
- dot 矩阵点乘
- trace 计算对角元素和
- det 计算矩阵的行列式
- eig 计算矩阵的特征值和特征向量
- inv 求逆矩阵
- qr 计算QR分解
- svd 计算奇异值分解(SVD)
- solve 求解x的线性系统Ax = b，其中A是方阵
- lstsq 计算AX = d 的最小二乘解

### 伪随机数生成
称之为伪随机数是因为这些随机数是由具有确定行为的算法根据随机数生成器中的随机数种子生成的，可以通过numpy.random.seed更改Numpy的随机数种子。numpy.random模块填补了Python内建random模块的不足，可以高效地生成多种概率分布下的完整样本值数组。然而内建的random模块一次只能生成一个值，下面是两种方法生成随机数的效率比较：

In [65]:
from random import normalvariate

N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

929 ms ± 27.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [66]:
%timeit np.random.normal(size=N)

29.5 ms ± 323 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


numpy.random中的部分函数列表：
- rand 从均匀分布中抽取样本
- randint 根绝给定的由高到低的范围抽取随机整数
- randn 从标准正态分布中抽取样本
- binomial 从二项分布抽取样本
- normal 从正态分布中抽取样本
- beta 从beta分布中抽取样本
- chisquare 从卡方分布中抽取样本
- gamma 从伽马分布中抽取样本
- uniform 从均匀[0, 1)分布中抽取样本